site_name: Dodo's Site
site_url: https://hungryDodo.github.io/
site_author: Dodo

theme:
  name: terminal
  features:
    - navigation.side.indexes
    - footer.prev_next
    - revision.date

nav:
  - Home: index.md
  - Academic:
    - Publications: academic/publications.md
    - Collaborations: academic/collaboration.md
  - Professional:
    - Service: professional/service.md
    - Projects: professional/projects.md
  - Public:
    - Blog: 
      - Index: public/blog.md
      - Blog01: public/blog/blog01.md
      - Blog02: public/blog/blog02.md
    - Tech: 
      - Index: public/tech.md
      - Tech01: public/tech/tech01.md
      - Tech02: public/tech/tech02.md
    - Welfare: public/welfare.md

markdown_extensions:
  # Python Markdown Extensions
  - admonition  # 提示框
  - attr_list  # 属性列表
  - def_list  # 定义列表
  - footnotes  # 脚注
  - tables  # 表格
  - md_in_html
  - meta  # 元数据
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference
  # PyMdown Extensions

  - pymdownx.blocks.details:
      types:
        - name: info 
          class: terminal-alert
          title: Info
        - name: warning
          class: 'terminal-alert terminal-alert-error'
          title: Warning
        - name: important
          class: 'terminal-alert terminal-alert-primary'
          title: Important
  - pymdownx.superfences  # 代码块嵌套
  - pymdownx.caret  # 上标和插入
  - pymdownx.mark  # 高亮
  - pymdownx.highlight  # 代码高亮
  - pymdownx.inlinehilite  # 内联高亮
  - pymdownx.superfences  # 代码块嵌套
  - pymdownx.tilde  # 波浪线
  - pymdownx.keys  # 快捷键
  - pymdownx.critic  # 批评
  - pymdownx.emoji  # 表情符号
  - pymdownx.tasklist  # 任务列表
  - pymdownx.arithmatex  # 数学公式
  - pymdownx.snippets:
      base_path:
        - docs

plugins:
  - search
  - git-revision-date
